#!/usr/bin/env python3
"""Generates crates/core/src/kanji_on_table.rs: one on'yomi per kanji.

    usage: scripts/gen_kanji_on.py <kanjidic2.xml | kanjidic2.xml.gz>

KANJIDIC2 is at https://www.edrdg.org/kanjidic/kanjd2index.html (Debian ships it
as the `kanjidic-xml` package, /usr/share/edict/kanjidic2.xml.gz). Kept: the
kyoiku, joyo and jinmeiyo kanji (grade 1-6, 8, 9, 10) that have an on'yomi; the
reading is the first `ja_on` KANJIDIC2 lists, as hiragana. Standard library only.
"""
import gzip
import sys
import xml.etree.ElementTree as ET

GRADES = {1, 2, 3, 4, 5, 6, 8, 9, 10}
OUT = "crates/core/src/kanji_on_table.rs"

HEADER = """\
// GENERATED by scripts/gen_kanji_on.py -- do not edit by hand.
//
// Source: KANJIDIC2 (kanjidic2.xml, file version {file_version}, database
// {database_version}), (c) the Electronic Dictionary Research and Development
// Group (EDRDG), https://www.edrdg.org/ -- licensed under Creative Commons
// Attribution-ShareAlike 4.0 (https://www.edrdg.org/edrdg/licence.html).
// This table is an adaptation of that data and stays under the same licence.
//
// One entry per kanji (grade 1-6, 8, 9, 10 with an on'yomi): the first on'yomi
// KANJIDIC2 lists, in hiragana. Sorted by character, for a binary search.

pub(crate) static TABLE: &[(char, &str)] = &[
"""


def hiragana(katakana: str) -> str:
    return "".join(
        chr(ord(c) - 0x60) if "ァ" <= c <= "ヶ" else c for c in katakana
    )


def main(path: str) -> None:
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rb") as f:
        root = ET.parse(f).getroot()
    header = root.find("header")
    rows = {}
    for c in root.findall("character"):
        grade = c.find("misc/grade")
        if grade is None or int(grade.text) not in GRADES:
            continue
        on = c.find('reading_meaning/rmgroup/reading[@r_type="ja_on"]')
        if on is None or not on.text:
            continue
        rows[c.find("literal").text] = hiragana(on.text.strip())
    out = HEADER.format(
        file_version=header.findtext("file_version"),
        database_version=header.findtext("database_version"),
    )
    for lit in sorted(rows):
        out += f'    (\'{lit}\', "{rows[lit]}"),\n'
    out += "];\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"{len(rows)} kanji -> {OUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
