[package]
name = "resonance-core"
version.workspace = true
authors = ["Enjay27 <kdkm2002@gmail.com>"]
description = "Platform-independent capture, protocol and text logic for Resonance Stream"
edition = "2021"
publish = false

[dependencies]
resonance-types = { path = "../types" }
chrono = { version = "0.4.43", default-features = false }
etherparse = "0.19.0"
kakasi = "0.1.0"
lazy_static = "1.5.0"
log = "0.4.29"
regex = "1.12.3"
semver = "1"
serde_json = "1"
sha2 = "0.10"
