use std::collections::HashMap;
use indexmap::IndexMap;
use leptos::prelude::{ReadSignal, RwSignal, WriteSignal};
use crate::types::{ChatMessage, SystemMessage};

#[derive(Copy, Clone, Debug)]
pub struct GlobalStore {
    // Add other global controls here
    pub init_done: ReadSignal<bool>,
    pub set_init_done: WriteSignal<bool>,
    pub use_translation: ReadSignal<bool>,
    pub set_use_translation: WriteSignal<bool>,
    pub compute_mode: ReadSignal<String>,
    pub set_compute_mode: WriteSignal<String>,
    pub wizard_step: ReadSignal<i32>,
    pub set_wizard_step: WriteSignal<i32>,
    pub is_translator_active: ReadSignal<bool>,
    pub set_is_translator_active: WriteSignal<bool>,
    pub is_sniffer_active: ReadSignal<bool>,
    pub set_is_sniffer_active: WriteSignal<bool>,
    pub status_text: ReadSignal<String>,
    pub set_status_text: WriteSignal<String>,
    pub model_ready: ReadSignal<bool>,
    pub set_model_ready: WriteSignal<bool>,
    pub downloading: ReadSignal<bool>,
    pub set_downloading: WriteSignal<bool>,
    pub progress: ReadSignal<u8>,
    pub set_progress: WriteSignal<u8>,
    pub active_tab: ReadSignal<String>,
    pub set_active_tab: WriteSignal<String>,
    pub search_term: ReadSignal<String>,
    pub set_search_term: WriteSignal<String>,
    pub name_cache: ReadSignal<HashMap<String, String>>,
    pub set_name_cache: WriteSignal<HashMap<String, String>>,
    pub chat_log: ReadSignal<IndexMap<u64, RwSignal<ChatMessage>>>,
    pub set_chat_log: WriteSignal<IndexMap<u64, RwSignal<ChatMessage>>>,
    pub system_log: ReadSignal<Vec<RwSignal<SystemMessage>>>,
    pub set_system_log: WriteSignal<Vec<RwSignal<SystemMessage>>>,
    pub is_system_at_bottom: ReadSignal<bool>,
    pub set_system_at_bottom: WriteSignal<bool>,
    pub show_system_tab: ReadSignal<bool>,
    pub set_show_system_tab: WriteSignal<bool>,
    pub system_level_filter: ReadSignal<Option<String>>,
    pub set_system_level_filter: WriteSignal<Option<String>>,
    pub system_source_filter: ReadSignal<Option<String>>,
    pub set_system_source_filter: WriteSignal<Option<String>>,
    pub compact_mode: ReadSignal<bool>,
    pub set_compact_mode: WriteSignal<bool>,
    pub is_pinned: ReadSignal<bool>,
    pub set_is_pinned: WriteSignal<bool>,
    pub show_settings: ReadSignal<bool>,
    pub set_show_settings: WriteSignal<bool>,
    pub chat_limit: ReadSignal<usize>,
    pub set_chat_limit: WriteSignal<usize>,
    pub custom_filters: ReadSignal<Vec<String>>,
    pub set_custom_filters: WriteSignal<Vec<String>>,
    pub theme: ReadSignal<String>,
    pub set_theme: WriteSignal<String>,
    pub opacity: ReadSignal<f32>,
    pub set_opacity: WriteSignal<f32>,
    pub is_debug: ReadSignal<bool>,
    pub set_is_debug: WriteSignal<bool>,
    pub tier: ReadSignal<String>,
    pub set_tier: WriteSignal<String>,
    pub restart_required: ReadSignal<bool>,
    pub set_restart_required: WriteSignal<bool>,
    pub dict_update_available: ReadSignal<bool>,
    pub set_dict_update_available: WriteSignal<bool>,
    pub is_at_bottom: ReadSignal<bool>,
    pub set_is_at_bottom: WriteSignal<bool>,
    pub unread_count: ReadSignal<i32>,
    pub set_unread_count: WriteSignal<i32>,
    pub active_menu_id: ReadSignal<Option<u64>>,
    pub set_active_menu_id: WriteSignal<Option<u64>>,
    pub archive_chat: ReadSignal<bool>,
    pub set_archive_chat: WriteSignal<bool>,
}